theme: jekyll-theme-minimal
title: cris8239's homepage
description: Bookmark this to keep an eye on my project updates!
logo: https://static.wikia.nocookie.net/fallout/images/6/61/Mainmenured.gif/revision/latest/scale-to-width-down/1200?cb=20111025173429
